default:
  models:
    MediaAppearance: read
    Wallpaper: read
    Wallpaper: read
    Event: read
    Book: read
    Wallpaper: read
    Site: read
    Team: read
    Membership:
      - read
      - search
    Platform::Application: read
    Webhooks::Outgoing::Endpoint: manage
    Webhooks::Outgoing::Event: read
    Webhooks::Outgoing::Delivery: read
    Webhooks::Outgoing::DeliveryAttempt: read
    Invitation:
      - read
      - create
      - destroy

editor:
  models:
    Scaffolding::CompletelyConcrete::TangibleThing: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcept:
      - read
      - update

admin:
  includes:
    - editor
  manageable_roles:
    - admin
    - editor
  models:
    MediaAppearance: manage
    Wallpaper: manage
    Wallpaper: manage
    Event: manage
    Book: manage
    Wallpaper: manage
    Site: manage
    Team: manage
    Membership: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcept: manage
    Platform::Application: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcepts::Collaborator: manage
