default:
  models:
    SettingBookCollectionPage: read
    SettingBiography: read
    MediaAppearance: read
    MediaAppearance: read
    BlogList: read
    BlogList: read
    BlogList: read
    BlogArticle: read
    BlogEntry: read
    BlogArticle: read
    BlogEntry: read
    Wallpaper: read
    Image: read
    Image: read
    Wallpaper: read
    Wallpaper: read
    Wallpaper: read
    Wallpaper: read
    Wallpaper: read
    Wallpaper: read
    Biography: read
    MerchandiseLink: read
    Image: read
    PublisherAccount: read
    MerchandiseLink: read
    MediaAppearance: read
    Wallpaper: read
    Wallpaper: read
    Event: read
    Book: read
    Wallpaper: read
    Site: read
    Team: read
    Membership:
      - read
      - search
    Platform::Application: read
    Webhooks::Outgoing::Endpoint: manage
    Webhooks::Outgoing::Event: read
    Webhooks::Outgoing::Delivery: read
    Webhooks::Outgoing::DeliveryAttempt: read
    Invitation:
      - read
      - create
      - destroy

editor:
  models:
    Scaffolding::CompletelyConcrete::TangibleThing: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcept:
      - read
      - update

admin:
  includes:
    - editor
  manageable_roles:
    - admin
    - editor
  models:
    SettingBookCollectionPage: manage
    SettingBiography: manage
    MediaAppearance: manage
    MediaAppearance: manage
    BlogList: manage
    BlogList: manage
    BlogList: manage
    BlogArticle: manage
    BlogEntry: manage
    BlogArticle: manage
    BlogEntry: manage
    Wallpaper: manage
    Image: manage
    Image: manage
    Wallpaper: manage
    Wallpaper: manage
    Wallpaper: manage
    Wallpaper: manage
    Wallpaper: manage
    Wallpaper: manage
    Biography: manage
    MerchandiseLink: manage
    Image: manage
    PublisherAccount: manage
    MerchandiseLink: manage
    MediaAppearance: manage
    Wallpaper: manage
    Wallpaper: manage
    Event: manage
    Book: manage
    Wallpaper: manage
    Site: manage
    Team: manage
    Membership: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcept: manage
    Platform::Application: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcepts::Collaborator: manage
